/*
 * TinyBioML — Pin & Hardware Configuration
 * Board: Arduino Nano 33 BLE Sense
 * MCU: nRF52840 (Cortex-M4F)
 * Model: KWS-Yes-No
 * Generated: 2026-04-02T18:40:07.808098
 *
 * AUTO-GENERATED by TinyBioML platform.
 * Redeploy to change pin assignments.
 */

#ifndef TINYBIOML_PIN_CONFIG_H
#define TINYBIOML_PIN_CONFIG_H

// =============================================================
// Board & Model Identity
// =============================================================
#define TBML_BOARD         "Arduino Nano 33 BLE Sense"
#define TBML_MCU           "nRF52840 (Cortex-M4F)"
#define TBML_MODEL         "KWS-Yes-No"

// =============================================================
// Serial Output
// =============================================================
#define TBML_BAUD          115200
#define TBML_JSON          1  // Always output JSON for web serial monitor

// =============================================================
// LED / Output Pins (active LOW on Nano 33 BLE)
// =============================================================
#define TBML_LED_BUILTIN   LED_BUILTIN

// Default: use onboard RGB LEDs
#define TBML_LED_CLASS_0   LEDR
#define TBML_LED_CLASS_1   LEDG
#define TBML_LED_CLASS_2   LEDB


// =============================================================
// Microphone Config
// =============================================================

#define TBML_MIC_DEFAULT   1       // Use board's default PDM mic

#define TBML_MIC_GAIN      20



#endif  // TINYBIOML_PIN_CONFIG_H