/*
 * TinyBioML — Keyword Spotting Firmware
 * Model: DS-CNN int8 (Speech Commands, 12 classes)
 * Board: Arduino Nano 33 BLE Sense
 * Input: Onboard PDM Microphone → MFCC [49, 13, 1]
 *
 * Classes: down, go, left, no, off, on, right, stop, up, yes, silence, unknown
 *
 * Preprocessing (must match training):
 *   16kHz audio → STFT(frame=640, hop=320, fft=1024) → 40 Mel bins → log → 13 MFCCs
 *
 * Generated by TinyBioML Platform
 */

#include <PDM.h>
#include <TensorFlowLite.h>
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/schema/schema_generated.h>

#include "model_data.h"

// =============================================================
// Configuration
// =============================================================
#define SAMPLE_RATE       16000
#define AUDIO_SAMPLES     16000     // 1 second of audio
#define NUM_MFCC_COEFFS   13
#define NUM_FRAMES        49
#define FFT_SIZE          1024
#define FRAME_LENGTH      640
#define FRAME_STEP        320
#define NUM_MEL_BINS      40
#define MEL_LOW_HZ        20.0f
#define MEL_HIGH_HZ       4000.0f
#define NUM_CLASSES        12

// Class labels (alphabetical order matching TFDS speech_commands)
const char* CLASS_NAMES[NUM_CLASSES] = {
  "down", "go", "left", "no", "off", "on",
  "right", "stop", "up", "yes", "silence", "unknown"
};

// =============================================================
// TFLite Micro
// =============================================================
namespace {
  const tflite::Model* model = nullptr;
  tflite::MicroInterpreter* interpreter = nullptr;
  TfLiteTensor* input_tensor = nullptr;
  TfLiteTensor* output_tensor = nullptr;

  constexpr int kTensorArenaSize = 100 * 1024;  // 100KB arena
  alignas(16) uint8_t tensor_arena[kTensorArenaSize];
}

// =============================================================
// Audio Buffers
// =============================================================
int16_t audioBuffer[AUDIO_SAMPLES];
volatile int samplesRead = 0;
volatile bool recordingDone = false;

// =============================================================
// DSP Buffers
// =============================================================
float fftReal[FFT_SIZE];
float fftImag[FFT_SIZE];
float melFilterbank[NUM_MEL_BINS][(FFT_SIZE / 2) + 1];
float mfccFeatures[NUM_FRAMES][NUM_MFCC_COEFFS];
float dctMatrix[NUM_MFCC_COEFFS][NUM_MEL_BINS];

// =============================================================
// Math Helpers
// =============================================================

float hzToMel(float hz) {
  return 2595.0f * log10f(1.0f + hz / 700.0f);
}

float melToHz(float mel) {
  return 700.0f * (powf(10.0f, mel / 2595.0f) - 1.0f);
}

// Simple in-place FFT (radix-2 Cooley-Tukey)
void fft(float* real, float* imag, int n) {
  // Bit-reverse permutation
  int j = 0;
  for (int i = 0; i < n - 1; i++) {
    if (i < j) {
      float tr = real[j]; real[j] = real[i]; real[i] = tr;
      float ti = imag[j]; imag[j] = imag[i]; imag[i] = ti;
    }
    int m = n >> 1;
    while (m >= 1 && j >= m) { j -= m; m >>= 1; }
    j += m;
  }

  // FFT butterfly
  for (int step = 1; step < n; step <<= 1) {
    float angle = -3.14159265358979f / (float)step;
    float wReal = cosf(angle);
    float wImag = sinf(angle);
    for (int group = 0; group < n; group += step << 1) {
      float curReal = 1.0f, curImag = 0.0f;
      for (int pair = 0; pair < step; pair++) {
        int idx1 = group + pair;
        int idx2 = idx1 + step;
        float tReal = curReal * real[idx2] - curImag * imag[idx2];
        float tImag = curReal * imag[idx2] + curImag * real[idx2];
        real[idx2] = real[idx1] - tReal;
        imag[idx2] = imag[idx1] - tImag;
        real[idx1] += tReal;
        imag[idx1] += tImag;
        float newReal = curReal * wReal - curImag * wImag;
        curImag = curReal * wImag + curImag * wReal;
        curReal = newReal;
      }
    }
  }
}

// =============================================================
// Initialize Mel Filterbank
// =============================================================
void initMelFilterbank() {
  float melLow = hzToMel(MEL_LOW_HZ);
  float melHigh = hzToMel(MEL_HIGH_HZ);
  int numBins = (FFT_SIZE / 2) + 1;  // 513

  float melPoints[NUM_MEL_BINS + 2];
  for (int i = 0; i < NUM_MEL_BINS + 2; i++) {
    melPoints[i] = melLow + (melHigh - melLow) * i / (NUM_MEL_BINS + 1);
  }

  float hzPoints[NUM_MEL_BINS + 2];
  for (int i = 0; i < NUM_MEL_BINS + 2; i++) {
    hzPoints[i] = melToHz(melPoints[i]);
  }

  int binPoints[NUM_MEL_BINS + 2];
  for (int i = 0; i < NUM_MEL_BINS + 2; i++) {
    binPoints[i] = (int)floorf((FFT_SIZE + 1) * hzPoints[i] / SAMPLE_RATE);
  }

  // Zero out
  memset(melFilterbank, 0, sizeof(melFilterbank));

  for (int m = 0; m < NUM_MEL_BINS; m++) {
    for (int k = binPoints[m]; k < binPoints[m + 1] && k < numBins; k++) {
      melFilterbank[m][k] = (float)(k - binPoints[m]) / (binPoints[m + 1] - binPoints[m]);
    }
    for (int k = binPoints[m + 1]; k < binPoints[m + 2] && k < numBins; k++) {
      melFilterbank[m][k] = (float)(binPoints[m + 2] - k) / (binPoints[m + 2] - binPoints[m + 1]);
    }
  }
}

// =============================================================
// Initialize DCT Matrix (for MFCC from log-mel)
// =============================================================
void initDCT() {
  for (int i = 0; i < NUM_MFCC_COEFFS; i++) {
    for (int j = 0; j < NUM_MEL_BINS; j++) {
      dctMatrix[i][j] = cosf(3.14159265358979f * i * (j + 0.5f) / NUM_MEL_BINS);
    }
  }
}

// =============================================================
// Compute MFCC for one frame of audio
// =============================================================
void computeFrameMFCC(int16_t* frame, int frameLen, float* mfccOut) {
  int numBins = (FFT_SIZE / 2) + 1;

  // Apply Hann window and load into FFT buffer
  for (int i = 0; i < FFT_SIZE; i++) {
    if (i < frameLen) {
      float window = 0.5f * (1.0f - cosf(2.0f * 3.14159265358979f * i / (frameLen - 1)));
      fftReal[i] = (frame[i] / 32768.0f) * window;
    } else {
      fftReal[i] = 0.0f;  // Zero-pad
    }
    fftImag[i] = 0.0f;
  }

  // FFT
  fft(fftReal, fftImag, FFT_SIZE);

  // Power spectrum
  float powerSpec[numBins];
  for (int i = 0; i < numBins; i++) {
    powerSpec[i] = sqrtf(fftReal[i] * fftReal[i] + fftImag[i] * fftImag[i]);
  }

  // Mel filterbank
  float melEnergies[NUM_MEL_BINS];
  for (int m = 0; m < NUM_MEL_BINS; m++) {
    melEnergies[m] = 0.0f;
    for (int k = 0; k < numBins; k++) {
      melEnergies[m] += powerSpec[k] * melFilterbank[m][k];
    }
    // Log
    melEnergies[m] = logf(melEnergies[m] + 1e-6f);
  }

  // DCT → MFCC
  for (int i = 0; i < NUM_MFCC_COEFFS; i++) {
    mfccOut[i] = 0.0f;
    for (int j = 0; j < NUM_MEL_BINS; j++) {
      mfccOut[i] += melEnergies[j] * dctMatrix[i][j];
    }
  }
}

// =============================================================
// Compute all MFCC frames from audio buffer
// =============================================================
void computeAllMFCCs() {
  for (int frame = 0; frame < NUM_FRAMES; frame++) {
    int offset = frame * FRAME_STEP;
    computeFrameMFCC(&audioBuffer[offset], FRAME_LENGTH, mfccFeatures[frame]);
  }
}

// =============================================================
// PDM Callback — fills audio buffer
// =============================================================
void onPDMdata() {
  int bytesAvailable = PDM.available();
  int samplesToRead = bytesAvailable / 2;

  if (recordingDone) return;

  int remaining = AUDIO_SAMPLES - samplesRead;
  if (samplesToRead > remaining) samplesToRead = remaining;

  PDM.read(&audioBuffer[samplesRead], samplesToRead * 2);
  samplesRead += samplesToRead;

  if (samplesRead >= AUDIO_SAMPLES) {
    recordingDone = true;
  }
}

// =============================================================
// Setup
// =============================================================
void setup() {
  Serial.begin(115200);
  while (!Serial) delay(10);

  Serial.println("{\"status\":\"boot\",\"msg\":\"TinyBioML Keyword Spotting\"}");
  Serial.println("{\"status\":\"init\",\"msg\":\"Loading model...\"}");

  // Load model
  model = tflite::GetModel(model_data);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    Serial.println("{\"status\":\"error\",\"msg\":\"Model schema mismatch\"}");
    while (1) delay(1000);
  }

  static tflite::AllOpsResolver resolver;
  static tflite::MicroInterpreter static_interpreter(
    model, resolver, tensor_arena, kTensorArenaSize);
  interpreter = &static_interpreter;

  if (interpreter->AllocateTensors() != kTfLiteOk) {
    Serial.println("{\"status\":\"error\",\"msg\":\"AllocateTensors failed\"}");
    while (1) delay(1000);
  }

  input_tensor = interpreter->input(0);
  output_tensor = interpreter->output(0);

  Serial.print("{\"status\":\"init\",\"msg\":\"Arena used: ");
  Serial.print(interpreter->arena_used_bytes());
  Serial.println(" bytes\"}");

  // Print input tensor info
  Serial.print("{\"status\":\"init\",\"msg\":\"Input shape: [");
  for (int i = 0; i < input_tensor->dims->size; i++) {
    Serial.print(input_tensor->dims->data[i]);
    if (i < input_tensor->dims->size - 1) Serial.print(",");
  }
  Serial.print("], type: ");
  Serial.print(input_tensor->type);
  Serial.println("\"}");

  // Initialize DSP
  initMelFilterbank();
  initDCT();

  // Initialize PDM microphone
  PDM.onReceive(onPDMdata);
  if (!PDM.begin(1, SAMPLE_RATE)) {
    Serial.println("{\"status\":\"error\",\"msg\":\"PDM microphone init failed\"}");
    while (1) delay(1000);
  }

  Serial.println("{\"status\":\"ready\",\"msg\":\"Listening...\",\"classes\":[\"down\",\"go\",\"left\",\"no\",\"off\",\"on\",\"right\",\"stop\",\"up\",\"yes\",\"silence\",\"unknown\"]}");
}

// =============================================================
// Main Loop
// =============================================================
void loop() {
  // Reset and start recording
  samplesRead = 0;
  recordingDone = false;

  // Wait for 1 second of audio
  while (!recordingDone) {
    delay(1);
  }

  // Compute MFCC features
  unsigned long featureStart = micros();
  computeAllMFCCs();
  unsigned long featureTime = micros() - featureStart;

  // Fill input tensor
  // Input is int8 — we need quantization params
  float input_scale = input_tensor->params.scale;
  int32_t input_zero_point = input_tensor->params.zero_point;

  for (int frame = 0; frame < NUM_FRAMES; frame++) {
    for (int coeff = 0; coeff < NUM_MFCC_COEFFS; coeff++) {
      float val = mfccFeatures[frame][coeff];
      // Quantize: int8_val = val / scale + zero_point
      int32_t quantized = (int32_t)roundf(val / input_scale) + input_zero_point;
      if (quantized < -128) quantized = -128;
      if (quantized > 127) quantized = 127;
      input_tensor->data.int8[frame * NUM_MFCC_COEFFS + coeff] = (int8_t)quantized;
    }
  }

  // Run inference
  unsigned long inferStart = micros();
  TfLiteStatus status = interpreter->Invoke();
  unsigned long inferTime = micros() - inferStart;

  if (status != kTfLiteOk) {
    Serial.println("{\"status\":\"error\",\"msg\":\"Inference failed\"}");
    return;
  }

  // Read output (int8) and dequantize
  float output_scale = output_tensor->params.scale;
  int32_t output_zero_point = output_tensor->params.zero_point;

  float scores[NUM_CLASSES];
  int bestClass = 0;
  float bestScore = -1e9;

  for (int i = 0; i < NUM_CLASSES; i++) {
    int8_t raw = output_tensor->data.int8[i];
    scores[i] = (raw - output_zero_point) * output_scale;
    if (scores[i] > bestScore) {
      bestScore = scores[i];
      bestClass = i;
    }
  }

  // Softmax normalization for display
  float maxScore = scores[0];
  for (int i = 1; i < NUM_CLASSES; i++) {
    if (scores[i] > maxScore) maxScore = scores[i];
  }
  float sumExp = 0;
  float probs[NUM_CLASSES];
  for (int i = 0; i < NUM_CLASSES; i++) {
    probs[i] = expf(scores[i] - maxScore);
    sumExp += probs[i];
  }
  for (int i = 0; i < NUM_CLASSES; i++) {
    probs[i] /= sumExp;
  }

  // Output as JSON for the web serial monitor
  Serial.print("{\"t\":");
  Serial.print(millis());
  Serial.print(",\"class\":");
  Serial.print(bestClass);
  Serial.print(",\"label\":\"");
  Serial.print(CLASS_NAMES[bestClass]);
  Serial.print("\",\"confidence\":");
  Serial.print(probs[bestClass], 4);
  Serial.print(",\"feature_us\":");
  Serial.print(featureTime);
  Serial.print(",\"infer_us\":");
  Serial.print(inferTime);
  Serial.print(",\"scores\":[");
  for (int i = 0; i < NUM_CLASSES; i++) {
    Serial.print(probs[i], 4);
    if (i < NUM_CLASSES - 1) Serial.print(",");
  }
  Serial.println("]}");

  // Small gap between recordings
  delay(100);
}
